### ISSUE TITLE
uoc notificier

### ISSUE THREAD

**Issue by xfernandezm** [crazyserver/UOC-notifier#12]

**Comment by sperramons** [comment]
NO se como funciona

**Comment by crazyserver** [comment]
Què problema tenéis?

**Comment by xfernandezm** [comment]
Ja est? solucionat.
Gr?cies.

Enviado desde mi iPhone

El 27/01/2016, a las 12:10, "Pau Ferrer Oca?a" <notifications@github.com<mailto:notifications@github.com>> escribi?:


Qu? problema ten?is?

-

**Comment by sperramons** [comment]
ja ho he resolt ! moltíssimes gràcies

2016-01-27 12:28 GMT+01:00 xfernandezm <notifications@github.com>:
