### ISSUE TITLE
Problema con asignaturas repetidas

### ISSUE THREAD

**Issue by digiolin** [crazyserver/UOC-notifier#13]
Buenas,

El problema es que me notifica de notas de EX y practicas de una asignatura que he repetido. Me notifica tanto de las notas actuales como de las antiguas. Y ahora por ejemplo me muestra la nota de examen y practica del otro semestre, cuando del actual aún no dispongo de la nota, ni con el truco del F12.

Gracias y un saludo!!

**Comment by crazyserver** [comment]
Que raro! Prueba reinstalar la extensión!

**Comment by crazyserver** [comment]
Actualiza a la versión 1.99 y en las opciones usa el botón de Reiniciar aulas ;)
