### ISSUE TITLE
Usuario/Password no es correcto

### ISSUE THREAD

**Issue by Brucie05** [crazyserver/UOC-notifier#14]
Intento acceder, pero cuando introduzco mis datos la página indica que el usuario/password no es correcto, sin embargo cuando accedo a la UOC si que me deja acceder.
He comprobado las opciones y todo es correcto.
¿que puedo hacer?

**Comment by crazyserver** [comment]
Seguramente es debido a que el servicio de autenticación de la UOC ha estado caído un rato. Si estas seguro de que está bien el que has introducido espera un rato, la misma extensión te avisará cuando haya hecho login. También puedes probar de hacer login en la app oficial de la UOC para Android ya que usa el mismo método. Creo que será un problema temporal ;)

**Comment by m4n4r4** [comment]
Hola, a mi me pasa lo mismo que a Brucie05. Desde hace una semana intento acceder al UOC notifier y no hay forma. La versión del addon es la última, así como la de Chrome. También he intentado acceder mediante la App de Android y el resultado es el mismo. En ambos casos me indica que el usuario y la contraseña son incorrectos. Sin embargo puedo acceder al campus con las mismas credenciales.

Por si sirve de ayuda mando una captura de pantalla.

Muchas gracias por el addon y el soporte!
<img width="1415" alt="captura de pantalla 2016-01-31 a les 13 54 40" src="https://cloud.githubusercontent.com/assets/12253921/12702410/a368cf92-c828-11e5-95e2-8b97e3cd29ca.png">

**Comment by crazyserver** [comment]
Hola, le habéis dado al enlace que sale en el mensaje de error? a veces el login se bloquea y hay que hacer entrar un recaptcha

**Comment by m4n4r4** [comment]
Hola, sí, también hemos intentando acceder mediante la página que solicita el captcha y no hay forma. E
Gracias!
