### ISSUE TITLE
Traducción incorrecta

### ISSUE THREAD

**Issue by e9169** [crazyserver/UOC-notifier#15]
En intervalo de comprobación, comprobación está escrito con V, y a los hispanohablantes nos duele ver cosas así. Por favor, corregidlo para próximas versiones.

**Comment by crazyserver** [comment]
Hace unas cuantas versiones que está corregido:
https://github.com/crazyserver/UOC-notifier/blob/master/_locales/es/messages.json#L25

Gracias por el aviso y un saludo!

**Comment by e9169** [comment]
Mmm. Ni idea. Yo instale el complemento hace apenas dos semanas por primera vez. Entiendo q se descarga la ultima versión disponible. 

Eneko Pérez
