### ISSUE TITLE
No funcionen els botons de l'aplicació

### ISSUE THREAD

**Issue by trotz** [crazyserver/UOC-notifier#19]
Hola,

Els botons de l'aplicació han deixat de funcionar. Si desintalo l'aplicació i la torno a instalar, funcionen uns minuts i després es tornen a bloquejar.

Les notificacions (de notes) semblen funcionar correctament.

**Comment by crazyserver** [comment]
Gracias! Entiendo que ya está solucionado en 1.115!

**Comment by trotz** [comment]
solved! ;)
